WIP: support CBC and CFB
wolfSSL/wolfTPM pull request #125
Opened 2020-09-28 23:30 UTC by elms

2020-09-29 16:02 UTC, dgarske requested changes

2020-09-29 16:02 UTC, dgarske commented on examples/wrap/wrap_test.c
> +        (byte*)TEST_AES_KEY, (word32)XSTRLEN(TEST_AES_KEY));
Using XSTRLEN here and below at 735 and 742 isn't going to work for either case (CFB or CBC)... one is string and one is byte array. Let's change them all to byte arrays and use sizeof().

2020-09-30 20:24 UTC, elms commented on examples/tpm_test.h
> +/* CBC is the more common mode supported by TPMs */
Done. I used your language in the comment.

2020-09-30 21:05 UTC, dgarske approved these changes

2020-09-30 21:05 UTC, merged