Added support for importing external private key to get a key blob
wolfSSL/wolfTPM pull request #132
Opened 2020-11-02 22:27 UTC by dgarske

ZD 11163.

2020-11-04 13:14 UTC, tomoveu reviewed
I could not spot anything out of the ordinary. My only two comments are about missing usage() prints for the user in the two new tools. Functionality wise they work and the code is easy to follow.

2020-11-04 13:14 UTC, tomoveu commented on examples/README.md
> +$ ./examples/keygen/keyimport keyblob.bin ECC
Once I looked at the code it became clear that we are importing hardcoded RSA key from tpm_test.h, but originally I thought we are important a plain key from keyblob.bin and then overwritting keyblob.bin with the same pair but as a TPM key. Perhaps one additional printf and/or usage when running keyload without parameters.

2020-11-04 13:14 UTC, tomoveu commented on examples/keygen/keyimport.c
> +        if (argc >= 3) {
There is no information to the user what is the default key scheme, when not specified. Maybe adding informative print about the options the tool is running with :)

2020-11-04 13:14 UTC, tomoveu commented on examples/keygen/keyimport.c
> +        if (argc >= 3) {
There is no information to the user what is the default key scheme, when not specified. Maybe adding informative print about the options the tool is running with

2020-11-12 14:19 UTC, tomoveu approved these changes
Great addition to the wolfTPM examples! I only had to do some minor changes about the keyload usage prints, whitespaces and README file. This is ready for merge :100:

2020-11-12 21:23 UTC, elms requested changes
Some compile isssues with `--disable-wolfcrypt` around unused variables and functions.

2020-11-12 21:52 UTC, elms approved these changes

2020-11-12 21:52 UTC, merged