Add seal example
wolfSSL/wolfTPM pull request #157
Opened 2021-04-16 07:44 UTC by tomoveu

This PR adds a seal example using a TPM 2.0 key

It makes use of the keygen/keyload example.

```
$ ./examples/seal/seal keyblob.bin mySecretMessage
TPM2.0 Simple Seal example
	Key Blob: keyblob.bin
	Use Parameter Encryption: NULL
Loading SRK: Storage 0x81000200 (282 bytes)
Sealing the user secret into a new TPM key
Created new TPM seal key (pub 46, priv 141 bytes)
Wrote 193 bytes to keyblob.bin
Key Public Blob 46
Key Private Blob 141
$ ./examples/keygen/keyload -persistent           
TPM2.0 Key load example
	Key Blob: keyblob.bin
	Use Parameter Encryption: NULL
Loading SRK: Storage 0x81000200 (282 bytes)
Reading 193 bytes from keyblob.bin
Reading the private part of the key
Loaded key to 0x80000001
Key was made persistent at 0x81000202
$ ./examples/seal/unseal message.raw
Example how to unseal data using TPM2.0
wolfTPM2_Init: success
Unsealing succeeded
Stored unsealed data to file = message.raw
$ cat message.raw 
mySecretMessage
```

2021-04-19 16:55 UTC, dgarske requested changes
Nice job on this @tomoveu . Just a couple minor items.

2021-04-19 16:55 UTC, dgarske commented on examples/README.md
> +$ ./examples/keygen/keyload -persistent
Please add new line between example commands for ease of reading.

2021-04-19 16:55 UTC, dgarske commented on examples/seal/seal.c
> +//#else
Please cleanup the print of the key blob. I recommend adding `#ifdef DEBUG_WOLFTPM` around it.

2021-04-19 16:55 UTC, dgarske commented on src/tpm2_wrap.c
> +    const byte* auth, int authSz, const byte* sealData, int sealSize)
In my tests the maximum size of sealSize was 128 bytes `MAX_SYM_DATA`. Please add some comments about this in examples/README.md and improve the error response on seal command.

2021-04-20 12:56 UTC, tomoveu commented
@dgarske all peer feedback taken in and I did two extra improvements

- let the developer choose the hashing algorithm of the (KEYEDHASH) Key Seal
- fixes for when wolfcrypt is disabled

I think we are ready for merge, let me know if I have to do some more changes.

2021-04-20 16:11 UTC, dgarske requested changes
Very nice work. Just two minor cleanups and it should be ready to go.

2021-04-20 16:11 UTC, dgarske commented on examples/seal/unseal.c
> +    const char *filename = "unseal.bin";
```
./configure --disable-wolfcrypt && make
...
examples/seal/unseal.c:54:17: error: variable ‘filename’ set but not used [-Werror=unused-but-set-variable]
     const char *filename = "unseal.bin";
                 ^~~~~~~~
```

2021-04-21 16:20 UTC, dgarske approved these changes

2021-04-21 16:21 UTC, merged