make: Rename NV example source files to avoid conflict
wolfSSL/wolfTPM pull request #159
Opened 2021-04-21 20:41 UTC by elms

New GPIO examples read conflicts on `make install`

2021-04-21 20:46 UTC, dgarske requested changes
Can we rename the more recent example for GPIO instead? I see the conflict on gpio/read.c and nvram/read.c. Suggest gpio_read.c and gpio_set.c.

2021-04-21 21:35 UTC, dgarske requested changes
Thank you, that's great. Can you also update the examples/README.md with the new names?

2021-04-21 21:45 UTC, dgarske approved these changes

2021-04-21 21:45 UTC, merged

2021-04-22 06:35 UTC, tomoveu commented
Thank you @elms for catching this! 🏅