Add experimental uboot support
wolfSSL/wolfTPM pull request #186
Opened 2021-07-29 15:27 UTC by tomoveu

This PR adds experimental u-boot support using new wolfTPM2 IO Callback and instructions for U-boot.

Partially tested.

2021-07-29 15:29 UTC, tomoveu commented
@dgarske this U-boot support is similar to our Barebox support, it requires manual steps on U-boot side that I tried to explain in README.md file.

I think it is ready for review.

2021-07-29 16:04 UTC, dgarske requested changes

2021-07-29 16:04 UTC, dgarske commented on examples/tpm_io_uboot.c
> +            return ret;
The return here will leave slave open. either release slave or better handle error code exit / return.

2021-07-29 16:04 UTC, dgarske commented on examples/tpm_io_uboot.c
> +        #error SPI check wait state logic not supported for U-boot
This could be a problem down the road, however the TPM commands you are using on the ST33 might not need it.

2021-07-29 16:04 UTC, dgarske commented on examples/u-boot/README.md
> +# Experimental support for U-boot
Can you described the platforms you tested on?

2021-07-29 16:46 UTC, tomoveu commented
@dgarske all peer feedback taken in. 

Good catch on the SPI release. Thanks!

2021-07-29 19:54 UTC, dgarske commented
@tomoveu , can you point us to the U-Boot fork with your changes?

2021-08-02 07:36 UTC, tomoveu commented
@dgarske let me clean it up a bit and I will drop a link. Should we add it into the README as well?

2021-08-02 18:57 UTC, dgarske commented
> @dgarske let me clean it up a bit and I will drop a link. Should we add it into the README as well?

Yes please

2021-11-08 19:54 UTC, closed without merging