Add support for ST33 vendor specific command `TPM_CC_GetRandom2`
wolfSSL/wolfTPM pull request #200
Opened 2022-01-24 16:57 UTC by dgarske

Allows getting DRBG data up to `TPM2B_MAX_BUFFER` in size. ZD13545

2022-01-26 00:31 UTC, elms reviewed
Looks good. 

I don't see a way to exercise this and test it.

2022-01-31 23:57 UTC, dgarske commented
Customer is happy with this. @elms over to you for final. Thanks

2022-02-01 17:50 UTC, dgarske commented
I will add a test case to call it for ST33 cases.

2022-02-04 00:21 UTC, elms requested changes

2022-02-04 00:21 UTC, elms commented on examples/native/native_test.c
> +#if defined(WOLFTPM_ST33) || defined(WOLFTPM_AUTODETECT)
It appears not all ST supports this. For that case if we see `TPM_RC_COMMAND_CODE` I think it should fall back to `TPM2_GetRandom` so this test can still pass on that hardware.

2022-02-09 17:46 UTC, elms approved these changes

2022-02-09 17:47 UTC, merged