Adding wrappers for CSR Generation
wolfSSL/wolfTPM pull request #219
Opened 2022-07-01 23:13 UTC by dgarske

Support for `wolfTPM2_CSR_Generate` and `wolfTPM2_CSR_Generate_TPM` wrappers to assist with CSR generation. Modified the existing CSR example to use wrapper.

2022-07-06 20:32 UTC, anhu requested changes
Sweet!  Think I caught some stuff.  Please look over my comments.

2022-07-06 20:32 UTC, anhu commented on wolftpm/tpm2_wrap.h
> +        wolfCrypt key (RsaKey or ecc_key)
This seems strange.  Why would you need a wolfcrypt key?  Isn't the key in the TPM? Below in param description it says its a loaded WOLFTPM2_KEY structure.

2022-07-06 20:32 UTC, anhu commented on src/tpm2_wrap.c
> +                                  DYNAMIC_TYPE_TMP_BUFFER);
needs one less white space

2022-07-06 20:32 UTC, anhu commented on src/tpm2_wrap.c
> +    for (i=0; i<(int)(sizeof(tags)/sizeof(DNTags)); i++) {
Empty line above this one please. ...also space before and after `/`

2022-07-06 20:32 UTC, anhu commented on src/tpm2_wrap.c
> +                len = CTC_NAME_SIZE-1; /* leave room for null term */
braces please.

2022-07-06 21:09 UTC, anhu commented on wrapper/CSharp/wolfTPM.cs
> +        ASN1 = 2,
Stupid nit: Can we change this to `DER` ?

2022-07-06 21:10 UTC, anhu approved these changes
Everything looks great to me.  Waiting for a few more changes as discussed privately.

2022-07-06 23:26 UTC, dgarske commented
Note: Going to be adding a WOLFTPM_CSR struct / class to support assembling a CSR then asking for it to be signed. This will allow for the custom request extension support.

2022-07-12 19:17 UTC, anhu commented on wolftpm/tpm2_wrap.h
> +        Zero (0) will generate a CSR to be used by a CA to sign and make into a "real" certificate.
In both cases, (zero, non-zero) this is a self signed object. (CA cert or CSR) .  Can you call this parameter `is_ca_cert` or something similar? (admittedly not the best name. )

2022-07-12 19:20 UTC, anhu commented on wrapper/CSharp/wolfTPM.cs
> +        public int SetCustomOid(string oid, string der, int critical)
Can this be renamed to `SetCustomExtension()` ?

2022-07-12 20:55 UTC, merged

2022-07-13 03:08 UTC, JasonMac219 commented on wrapper/CSharp/wolfTPM-tests.cs
> +            ret = device.GenerateCSR(keyBlob, subject, keyUsage,
Could add subject format requirements for this interface.