add example manual verification of quote signature with ecc
wolfSSL/wolfTPM pull request #379
Opened 2024-09-13 18:10 UTC by JacobBarthelmeh

2024-09-17 18:12 UTC, dgarske requested changes
Is it possible you could add support for this with RSA also?

2024-09-20 17:04 UTC, JacobBarthelmeh commented on examples/pcr/quote.c
> +        printf("%s [rc = %d, result = %d]\n", (res == 1)? "SUCCESS": "FAILURE",
Possibly different for swtpm used? Try with ms-tpm-20-ref. I made a commit now updating the docs/SWTPM.md with steps for a test done.

2024-09-20 17:10 UTC, JacobBarthelmeh commented
Yup, can add in RSA. Would like to follow up with it though in a separate PR, keeping this one with as few code changes as can for the use.

2024-09-21 00:15 UTC, dgarske approved these changes
Works for me now! Thank you

2024-09-23 18:35 UTC, merged